# Images
## This notebook outlines the math of the Image manipulation used in OpenCV library

- Image Math
- Numpy Arrays

**Image Operations**
- add
- subtract
- bitwise

### Import the necessary libraries

In [5]:
from __future__ import print_function
import argparse
import cv2
import numpy as np

### Load an image
#### imread( )

In [6]:
image = cv2.imread("image.jpg")

In [7]:
image

array([[[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 240, 244],
        [233, 236, 240],
        [227, 230, 234]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 240, 244],
        [235, 238, 242],
        [231, 234, 238]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [238, 239, 243],
        [235, 238, 242],
        [232, 235, 239]],

       ...,

       [[246, 241, 238],
        [246, 241, 238],
        [246, 241, 238],
        ...,
        [242, 237, 236],
        [242, 237, 236],
        [242, 237, 236]],

       [[246, 241, 238],
        [246, 241, 238],
        [246, 241, 238],
        ...,
        [243, 238, 237],
        [243, 238, 237],
        [243, 238, 237]],

       [[247, 242, 239],
        [247, 242, 239],
        [247, 242, 239],
        ...,
        [243, 238, 237],
        [243, 238, 237],
        [243, 238, 237]]

Images are NumPy arrays, stored as unsigned 8 bit integers.

- values of our image's pixels will **always** be in the range [0, 255]. 
- Why???

In [13]:
print(f"wrap around: {np.uint8([200]) + np.uint8([100])}")
print(f"wrap around: {np.uint8([50]) - np.uint8([100])}")

wrap around: [44]
wrap around: [206]


### Overflow the add and subtract functions

In [14]:
print(f"Max of 255: {cv2.add(np.uint8([200]), np.uint8([100]))}")
print(f"Min of 0: {cv2.subtract(np.uint8([50]), np.uint8([100]))}")

Max of 255: [[255]]
Min of 0: [[0]]


## Image Methods
- cv2.add( )
- cv2.subtract ( )

## cv2.add( )

**Image enhancer**
- Increase the intensity of all pixels in our image by 100

Steps
- Constructing a NumPy array that is the same size of our matrix (filled with ones)
- Multiplying it by 100 to create an array filled with 100's. 
- Simply add the images together

You will notice how the image is "brighter" than the original.



In [15]:
M = np.ones(image.shape, dtype = "uint8") * 100
M

array([[[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       ...,

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]]

In [16]:
image

array([[[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 240, 244],
        [233, 236, 240],
        [227, 230, 234]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 240, 244],
        [235, 238, 242],
        [231, 234, 238]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [238, 239, 243],
        [235, 238, 242],
        [232, 235, 239]],

       ...,

       [[246, 241, 238],
        [246, 241, 238],
        [246, 241, 238],
        ...,
        [242, 237, 236],
        [242, 237, 236],
        [242, 237, 236]],

       [[246, 241, 238],
        [246, 241, 238],
        [246, 241, 238],
        ...,
        [243, 238, 237],
        [243, 238, 237],
        [243, 238, 237]],

       [[247, 242, 239],
        [247, 242, 239],
        [247, 242, 239],
        ...,
        [243, 238, 237],
        [243, 238, 237],
        [243, 238, 237]]

In [17]:
added_image = cv2.add(image, M)
added_image

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [19]:
cv2.imshow("Original", image)
cv2.imshow("Added", added_image)
cv2.waitKey(0)

13

## Task: Take a low-contrast image from your desktop and enhance it
- Load the low-contrast image
- Study the loaded images' details
- Create a brighter mask as above as the same size of the laoded image
- Use cv2.add( ) to perform image enhancement

## cv2. subtract ( )
**Image enhancer**
- Decrease the intensity of all pixels in our image by 100

Steps
- Constructing a NumPy array that is the same size of our matrix (filled with ones)
- Multiplying it by 100 to create an array filled with 100's. 
- Simply subtract the images together

You will notice how the image is "darker" than the original.


In [20]:
M = np.ones(image.shape, dtype = "uint8") * 100
M

array([[[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       ...,

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]]

In [22]:
subtracted_image = cv2.subtract(image, M)
subtracted_image

array([[[154, 154, 154],
        [154, 154, 154],
        [154, 154, 154],
        ...,
        [137, 140, 144],
        [133, 136, 140],
        [127, 130, 134]],

       [[154, 154, 154],
        [154, 154, 154],
        [154, 154, 154],
        ...,
        [137, 140, 144],
        [135, 138, 142],
        [131, 134, 138]],

       [[154, 154, 154],
        [154, 154, 154],
        [154, 154, 154],
        ...,
        [138, 139, 143],
        [135, 138, 142],
        [132, 135, 139]],

       ...,

       [[146, 141, 138],
        [146, 141, 138],
        [146, 141, 138],
        ...,
        [142, 137, 136],
        [142, 137, 136],
        [142, 137, 136]],

       [[146, 141, 138],
        [146, 141, 138],
        [146, 141, 138],
        ...,
        [143, 138, 137],
        [143, 138, 137],
        [143, 138, 137]],

       [[147, 142, 139],
        [147, 142, 139],
        [147, 142, 139],
        ...,
        [143, 138, 137],
        [143, 138, 137],
        [143, 138, 137]]

In [23]:
cv2.imshow("Original", image)
cv2.imshow("Subtracted", subtracted_image)
cv2.waitKey(0)

13

## Task: Take a high-contrast image from your desktop and enhance it
- Load the washed-out high-contrast image
- Study the loaded images' details
- Create a darker mask as above as the same size of the laoded image
- Use cv2.subtract( ) to perform image enhancement

## Bitwise operations
- AND
- OR
- XOR
- NOT

### Draw a rectangle

In [25]:
rectangle = np.zeros((300, 300), dtype = "uint8")
cv2.rectangle(rectangle, (25, 25), (275, 275), 255, -1)
cv2.imshow("Rectangle", rectangle)
cv2.waitKey(0)

13

### Draw a circle

In [26]:
circle = np.zeros((300, 300), dtype = "uint8")
cv2.circle(circle, (150, 150), 150, 255, -1)
cv2.imshow("Circle", circle)
cv2.waitKey(0)

13

### Bitwise AND
#### A bitwise 'AND' is only True when both rectangle and circle have a value that is 'ON'. 

- If both pixels have a value greater than zero, that pixel is turned 'ON' (i.e set to 255 in the output image). 
- If both pixels are not greater than zero, then the output pixel is left 'OFF' with a value of 0.

In [27]:
bitwiseAnd = cv2.bitwise_and(rectangle, circle)
cv2.imshow("AND", bitwiseAnd)
cv2.waitKey(0)

13

### Bitwise OR
#### A bitwise 'OR' is only True when either rectangle or circle have a value that is 'ON'. 

- If either pixels have a value greater than zero, that pixel is turned 'ON' (i.e set to 255 in the output image). 
- If both pixels are not greater than zero, then the output pixel is left 'OFF' with a value of 0.

In [28]:
bitwiseOr = cv2.bitwise_or(rectangle, circle)
cv2.imshow("OR", bitwiseOr)
cv2.waitKey(0)

13

### Bitwise XOR
#### A bitwise 'XOR' is identical to the 'OR' function, with one exception: 

- both rectangle and circle are not allowed to have values greater than 0.

In [29]:
bitwiseXor = cv2.bitwise_xor(rectangle, circle)
cv2.imshow("XOR", bitwiseXor)
cv2.waitKey(0)

13

### Bitwise NOT
### The bitwise 'NOT' inverts the values of the pixels
- Pixels with a value of 255 become 0
- Pixels with a value of 0 become 255

In [31]:
bitwiseNotCircle = cv2.bitwise_not(circle)
cv2.imshow("NOT CIRCLE", bitwiseNotCircle)

bitwiseNotRect = cv2.bitwise_not(rectangle)
cv2.imshow("NOT RECT", bitwiseNotRect)
cv2.waitKey(0)

13