# Images
## This notebook outlines the different Color Spaces used in OpenCV library

**Image ColorSpaces**
- Color
    - RGB
    - HSV
    - L*a*b
- GrayScale

### Import the necessary libraries

In [2]:
from __future__ import print_function
import argparse
import cv2
import numpy as np

### Load an image
#### imread( )

In [3]:
image = cv2.imread("image.jpg")

In [4]:
image

array([[[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 240, 244],
        [233, 236, 240],
        [227, 230, 234]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 240, 244],
        [235, 238, 242],
        [231, 234, 238]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [238, 239, 243],
        [235, 238, 242],
        [232, 235, 239]],

       ...,

       [[246, 241, 238],
        [246, 241, 238],
        [246, 241, 238],
        ...,
        [242, 237, 236],
        [242, 237, 236],
        [242, 237, 236]],

       [[246, 241, 238],
        [246, 241, 238],
        [246, 241, 238],
        ...,
        [243, 238, 237],
        [243, 238, 237],
        [243, 238, 237]],

       [[247, 242, 239],
        [247, 242, 239],
        [247, 242, 239],
        ...,
        [243, 238, 237],
        [243, 238, 237],
        [243, 238, 237]]

### Load your favorite image and display it


In [5]:
image = cv2.imread("image.jpg")
cv2.imshow("Original", image)
cv2.waitKey(0)

13

## ColorSpaces
- BGR

### Load the image and grab each channel: Red, Green, and Blue

NOTE: OpenCV stores an image as NumPy array with its channels in reverse order! 

When we call cv2.split, we are actually getting the channels as Blue, Green, Red!

### Split a Color Image into channels

In [6]:
image = cv2.imread("image.jpg")
(B, G, R) = cv2.split(image)

### Display channels in an image

In [7]:
cv2.imshow("Red", R)
cv2.imshow("Green", G)
cv2.imshow("Blue", B)
cv2.waitKey(0)

13

### Merge different channels into an image

In [8]:
merged = cv2.merge([B, G, R])
cv2.imshow("Merged", merged)
cv2.waitKey(0)

13

In [10]:
zeros = np.zeros(image.shape[:2], dtype = "uint8")
cv2.imshow("Red", cv2.merge([zeros, zeros, R]))
cv2.imshow("Green", cv2.merge([zeros, G, zeros]))
cv2.imshow("Blue", cv2.merge([B, zeros, zeros]))
cv2.waitKey(0)

13

In [11]:
cv2.destroyAllWindows()

### Convert the original image into a GrayScale image
- Use cv2.COLOR_BGR2GRAY

In [33]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray", gray)
cv2.waitKey(0)

13

### Let's look at the math of this grayscale image

In [34]:
gray

array([[254, 254, 254, ..., 241, 237, 231],
       [254, 254, 254, ..., 241, 239, 235],
       [254, 254, 254, ..., 240, 239, 236],
       ...,
       [241, 241, 241, ..., 237, 237, 237],
       [241, 241, 241, ..., 238, 238, 238],
       [242, 242, 242, ..., 238, 238, 238]], dtype=uint8)

In [36]:
gray.shape

(228, 350)

In [35]:
image

array([[[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 240, 244],
        [233, 236, 240],
        [227, 230, 234]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [237, 240, 244],
        [235, 238, 242],
        [231, 234, 238]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [238, 239, 243],
        [235, 238, 242],
        [232, 235, 239]],

       ...,

       [[246, 241, 238],
        [246, 241, 238],
        [246, 241, 238],
        ...,
        [242, 237, 236],
        [242, 237, 236],
        [242, 237, 236]],

       [[246, 241, 238],
        [246, 241, 238],
        [246, 241, 238],
        ...,
        [243, 238, 237],
        [243, 238, 237],
        [243, 238, 237]],

       [[247, 242, 239],
        [247, 242, 239],
        [247, 242, 239],
        ...,
        [243, 238, 237],
        [243, 238, 237],
        [243, 238, 237]]

In [37]:
image.shape

(228, 350, 3)

### Convert the original image to the HSV (Hue, Saturation, Value)

In [38]:
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
cv2.imshow("HSV", hsv)
cv2.waitKey(0)

13

### Convert the original image into L*a*b Color Space

In [39]:
lab = cv2.cvtColor(image, cv2.COLOR_BGR2LAB)
cv2.imshow("L*a*b*", lab)
cv2.waitKey(0)

13